// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnirccqpzhfjhsqdhjdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuaXJjY3FwemhmamhzcWRoamRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNDUwMjgsImV4cCI6MjA1MDYyMTAyOH0.jlLm0_8JmdXPQUKCf7jvQl7W0sPZP6tcRZ2ffpXeFLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);